GET http://0.0.0.0:8080/@spatial/turf /1.0.5/lol.pom

###

GET https://registry.npmjs.org/@spatial/turf
###

GET http://0.0.0.0:8080/npm/iconv-lite/0.4.24/lol.module

###
// @no-redirect
GET  https://registry.npmjs.org/lodash

###

GET https://registry.npmjs.org/lodash


